# Sidebar navigation

- label: 'about'
  link: '/'
- label: 'now'
  link: '/now'
- label: Projects
  items:
    - label: 'reading'
      link: '/reading'
    - label: 'learning'
      link: '/learning'
    - label: 'misc'
      link: '/misc'
